
/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.regex.Pattern;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        // System.out.println(new App().getGreeting());
        System.out.println(new QRCodeGen("Gov1nda+ -$:%*").getInputString());
    }
}

enum ErrorCorrectionLevel {
    L, M, Q, H
}

class QRCodeGen {
    private String inputString;
    // private ErrorCorrectionLevel errorCorrectionLevel = ErrorCorrectionLevel.M;

    QRCodeGen(String input) throws Exception {
        inputString = input;
        System.out.println(validateAlphanumeric());
        if (!validateAlphanumeric()) {
            throw new Exception(
                    "BAD VALIDATION: input string should have characters only within the alphanumeric QR Code spec");
        }
    }

    public String getInputString() {
        return inputString;
    }

    private boolean validateAlphanumeric() {
        // -$%*/.
        Pattern alphanum = Pattern.compile("[^a-zA-Z0-9+$%*: -]");
        return !alphanum.matcher(inputString).find();

    }

}
